af.send
af.sendExt
af.zclAttrsReq 
af.zclFoundation 
af.zclFunctional

dispatchIncomingMsg
dataConfirmHandler
reflectErrorHandler
incomingMsgHandler
incomingMsgExtHandler
zclIncomingMsgHandler

zclIncomingParsedMsgEmitter
makeAfParams
makeAfParamsExt
isApsAckEventPending
createApsAckListener
clearApsAckListener
isZclRspEventPending
createZclRspListener
clearZclRspListener
hasListenerOnController

// ok
nextSeqNum
// ok
toLongAddrString
